Repository TwoSSome/backend, pull requests merged in 2024-11, with the labels that each got.

#127 리뷰글 item(품목) 열 추가 및 item으로 네이버 쇼핑몰 url get
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: enhancement

#128 Feature/fix
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostUpdateDto.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/repository/reviewpost/ReviewPostRepository.java
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: fix

#130 댓글 member null일 때 예외처리
  src/main/java/towssome/server/service/CommentLikeService.java
  src/main/java/towssome/server/service/CommentService.java
Labels: fix

#131 개인정보 찾기 기능 추가
  src/main/java/towssome/server/advice/MailSendAdvice.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/dto/EmailAuthNumReq.java
  src/main/java/towssome/server/dto/EmailUsernameReq.java
  src/main/java/towssome/server/dto/PasswordReq.java
  src/main/java/towssome/server/dto/UsernameRes.java
  src/main/java/towssome/server/entity/EmailVerification.java
  src/main/java/towssome/server/enumrated/EmailType.java
  src/main/java/towssome/server/repository/EmailVerificationRepository.java
  src/main/java/towssome/server/repository/member/MemberRepositoryCustom.java
  src/main/java/towssome/server/repository/member/MemberRepositoryImpl.java
  src/main/java/towssome/server/service/JoinService.java
  src/main/java/towssome/server/service/MemberService.java
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: enhancement

#133 리뷰글 추천
  src/main/java/towssome/server/controller/QuickRecommendController.java
  src/main/java/towssome/server/controller/RecommendController.java
  src/main/java/towssome/server/entity/SearchHistory.java
  src/main/java/towssome/server/repository/SearchHistoryRepository.java
  src/main/java/towssome/server/repository/cluster/ClusterRepository.java
  src/main/java/towssome/server/repository/cluster/ClusterRepositoryCustom.java
  src/main/java/towssome/server/repository/cluster/ClusterRepositoryImpl.java
  src/main/java/towssome/server/repository/comment/CommentRepositoryImpl.java
  src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryCustom.java
  src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryImpl.java
  src/main/java/towssome/server/repository/member/MemberRepository.java
  src/main/java/towssome/server/repository/reviewpost/ReviewPostRepositoryCustom.java
  src/main/java/towssome/server/repository/reviewpost/ReviewPostRepositoryImpl.java
  src/main/java/towssome/server/repository/viewlike/ViewLikeRepository.java
  src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryImpl.java
  src/main/java/towssome/server/service/ClusterService.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/RecommendService.java
  src/main/java/towssome/server/service/SearchHistoryService.java
Labels: enhancement

#134 댓글 프로필 정보 추가
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/dto/CommentRes.java
  src/main/java/towssome/server/dto/ProfileSimpleRes.java
  src/main/java/towssome/server/service/CommentService.java
Labels: fix

#136 검색 결과 없을 시 추천 태그
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/RecommendController.java
  src/main/java/towssome/server/dto/ListResultRes.java
  src/main/java/towssome/server/dto/QuickRecommendReq.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/python/tagRecommend.py
  src/main/java/towssome/server/python/userClustering.py
  src/main/java/towssome/server/repository/hashtag/HashTagRepositoryCustom.java
  src/main/java/towssome/server/repository/hashtag/HashTagRepositoryImpl.java
  src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryCustom.java
  src/main/java/towssome/server/repository/hashtag_classification/HashtagClassificationRepositoryImpl.java
  src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/viewlike/ViewLikeRepositoryImpl.java
  src/main/java/towssome/server/service/HashtagService.java
  src/main/java/towssome/server/service/RecommendService.java
Labels: enhancement

#135 RT 관련 버그 수정
  src/main/java/towssome/server/jwt/LoginFilter.java
  src/main/java/towssome/server/jwt/RefreshTokenRepository.java
  src/main/java/towssome/server/jwt/ReissueController.java
Labels: fix

#137 패스워드 재설정 로직 변경
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/controller/OAuthController.java
  src/main/java/towssome/server/dto/AccessRefreshRes.java
  src/main/java/towssome/server/dto/ErrorResult.java
  src/main/java/towssome/server/dto/JwtRes.java
  src/main/java/towssome/server/dto/PasswordReq.java
  src/main/java/towssome/server/jwt/JwtStatic.java
  src/main/java/towssome/server/jwt/JwtUtil.java
  src/main/java/towssome/server/service/MemberService.java
Labels: fix

#138 fix(Login): 로그인 시 트랜잭션 문제 수정
  src/main/java/towssome/server/jwt/JwtUtil.java
  src/main/java/towssome/server/jwt/LoginFilter.java
Labels: bug

#139 hashtag 수정
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/HashtagService.java
Labels: fix

#142 feat(CICD): cicd 기능 추가
  .github/workflows/jib-build.yaml
  .gitignore
  build.gradle
  src/main/resources/application-prod.properties
Labels: enhancement

#158 검색 시 검색어(해시태그) 추천 수정 & 프로필 팔로우 추천 수정
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/RecommendController.java
  src/main/java/towssome/server/dto/ProfileRes_.java
  src/main/java/towssome/server/dto/RecommendTagRes.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/python/tagRecommend.py
  src/main/java/towssome/server/repository/cluster/ClusterRepository.java
  src/main/java/towssome/server/repository/cluster/ClusterRepositoryCustom.java
  src/main/java/towssome/server/repository/cluster/ClusterRepositoryImpl.java
  src/main/java/towssome/server/repository/hashtag/HashTagRepositoryImpl.java
  src/main/java/towssome/server/repository/member/MemberRepository.java
  src/main/java/towssome/server/repository/member/MemberRepositoryCustom.java
  src/main/java/towssome/server/service/RecommendService.java
Labels: fix
