Repository TwoSSome/backend, pull requests merged in 2024-05, with the labels that each got.

#21 review CRUD
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/ReviewPostDTO.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/dto/ReviewPostUpdateDto.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/repository/PhotoRepository.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/service/PhotoService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/resources/data.sql
Labels: enhancement

#23 투표 기능 추가 및 review 로직 수정
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/CommunityPostRes.java
  src/main/java/towssome/server/dto/CommunityPostSaveDTO.java
  src/main/java/towssome/server/dto/CommunityPostSaveReq.java
  src/main/java/towssome/server/dto/CommunityPostUpdateReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/dto/VoteAttributeDTO.java
  src/main/java/towssome/server/dto/VoteAttributeReq.java
  src/main/java/towssome/server/dto/VoteAttributeRes.java
  src/main/java/towssome/server/dto/VoteMember.java
  src/main/java/towssome/server/dto/VoteReq.java
  src/main/java/towssome/server/dto/VoteRes.java
  src/main/java/towssome/server/dto/VoteSaveDTO.java
  src/main/java/towssome/server/dto/VoteSaveReq.java
  src/main/java/towssome/server/entity/Anniversary.java
  src/main/java/towssome/server/entity/BaseEntity.java
  src/main/java/towssome/server/entity/BookMark.java
  src/main/java/towssome/server/entity/Category.java
  src/main/java/towssome/server/entity/CategoryClassification.java
  src/main/java/towssome/server/entity/Cluster.java
  src/main/java/towssome/server/entity/Comment.java
  src/main/java/towssome/server/entity/CommunityPost.java
  src/main/java/towssome/server/entity/HashTag.java
  src/main/java/towssome/server/entity/HashtagClassification.java
  src/main/java/towssome/server/entity/Member.java
  src/main/java/towssome/server/entity/Photo.java
  src/main/java/towssome/server/entity/Reply.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/entity/Subscribe.java
  src/main/java/towssome/server/entity/ViewLike.java
  src/main/java/towssome/server/entity/Vote.java
  src/main/java/towssome/server/entity/VoteAttribute.java
  src/main/java/towssome/server/entity/VoteAttributeMember.java
  src/main/java/towssome/server/enumrated/PhotoType.java
  src/main/java/towssome/server/repository/MemberRepository.java
  src/main/java/towssome/server/repository/VoteAttributeMemberRepository.java
  src/main/java/towssome/server/repository/VoteAttributeRepository.java
  src/main/java/towssome/server/repository/VoteRepository.java
  src/main/java/towssome/server/service/CommunityService.java
  src/main/java/towssome/server/service/PhotoService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/VoteService.java
Labels: enhancement

#24 jwt 인증/인가 방식 설정
  build.gradle
  src/main/java/towssome/server/advice/ExceptionAdvice.java
  src/main/java/towssome/server/config/CorsConfig.java
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/dto/JoinReq.java
  src/main/java/towssome/server/entity/Member.java
  src/main/java/towssome/server/entity/RefreshToken.java
  src/main/java/towssome/server/jwt/CustomLogoutFilter.java
  src/main/java/towssome/server/jwt/CustomUserDetailService.java
  src/main/java/towssome/server/jwt/CustomUserDetails.java
  src/main/java/towssome/server/jwt/JoinDTO.java
  src/main/java/towssome/server/jwt/JoinService.java
  src/main/java/towssome/server/jwt/JwtFilter.java
  src/main/java/towssome/server/jwt/JwtUtil.java
  src/main/java/towssome/server/jwt/LoginFilter.java
  src/main/java/towssome/server/jwt/RefreshTokenRepository.java
  src/main/java/towssome/server/jwt/ReissueController.java
  src/main/java/towssome/server/repository/MemberRepository.java
  src/main/java/towssome/server/service/MemberService.java
Labels: enhancement

#25 Comment CRUD
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/dto/CommentDTO.java
  src/main/java/towssome/server/dto/CommentReq.java
  src/main/java/towssome/server/dto/CommentRes.java
  src/main/java/towssome/server/dto/CommentUpdateDto.java
  src/main/java/towssome/server/dto/CommentUpdateReq.java
  src/main/java/towssome/server/repository/CommentRepository.java
  src/main/java/towssome/server/service/CommentService.java
Labels: enhancement

#27 카테고리 기능 추가
  src/main/java/towssome/server/controller/BookMarkController.java
  src/main/java/towssome/server/controller/CategoryController.java
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/AddBookmarkReq.java
  src/main/java/towssome/server/dto/CategoryRes.java
  src/main/java/towssome/server/dto/CreateCategoryDTO.java
  src/main/java/towssome/server/dto/UpdateCategoryDTO.java
  src/main/java/towssome/server/dto/UpdateCategoryReq.java
  src/main/java/towssome/server/entity/BookMark.java
  src/main/java/towssome/server/entity/Category.java
  src/main/java/towssome/server/entity/CategoryClassification.java
  src/main/java/towssome/server/entity/Photo.java
  src/main/java/towssome/server/exception/NotFoundBookMarkException.java
  src/main/java/towssome/server/exception/NotFoundCategoryException.java
  src/main/java/towssome/server/jwt/JoinService.java
  src/main/java/towssome/server/repository/BookMarkRepository.java
  src/main/java/towssome/server/repository/CategoryClassificationRepository.java
  src/main/java/towssome/server/repository/CategoryRepository.java
  src/main/java/towssome/server/service/BookMarkService.java
  src/main/java/towssome/server/service/CommunityService.java
  src/main/java/towssome/server/service/MemberService.java
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: enhancement

#29 좋아요/최근 조회
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/dto/ViewLikeReq.java
  src/main/java/towssome/server/entity/ViewLike.java
  src/main/java/towssome/server/repository/ViewLikeRepository.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: enhancement

#32 리뷰글 단건 조회 수정
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/repository/BookMarkRepository.java
  src/main/java/towssome/server/repository/BookMarkRepositoryCustom.java
  src/main/java/towssome/server/repository/BookMarkRepositoryImpl.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/repository/ViewLikeRepository.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: fix

#33 구독 기능 추가
  src/main/java/towssome/server/advice/MemberAdvice.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/controller/SubscribeController.java
  src/main/java/towssome/server/dto/SubscribeAddDTO.java
  src/main/java/towssome/server/dto/SubscribeDTO.java
  src/main/java/towssome/server/dto/SubscribeRes.java
  src/main/java/towssome/server/dto/SubscribeSliceDTO.java
  src/main/java/towssome/server/entity/Subscribe.java
  src/main/java/towssome/server/repository/SubscribeRepository.java
  src/main/java/towssome/server/repository/SubscribeRepositoryCustom.java
  src/main/java/towssome/server/repository/SubscribeRepositoryImpl.java
  src/main/java/towssome/server/service/SubscribeService.java
Labels: enhancement

#34 함수에 Security 적용 및 반환 요소(Entity -> DTO) 수정
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/dto/ViewLikeReq.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: fix

#43 커뮤니티 본문 검색 기능 외 버그 수정
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/dto/CommunitySearchCondition.java
  src/main/java/towssome/server/entity/CommunityPost.java
  src/main/java/towssome/server/entity/Vote.java
  src/main/java/towssome/server/repository/CommunityPostRepositoryImpl.java
  src/main/java/towssome/server/service/CommunityService.java
  src/main/java/towssome/server/service/PhotoService.java
  src/main/java/towssome/server/service/VoteService.java
Labels: bug, enhancement

#44 커뮤니티글 익명 전환 기능 및 투표 기능
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/VoteController.java
  src/main/java/towssome/server/dto/CommunityPostRes.java
  src/main/java/towssome/server/dto/CommunityPostSaveDTO.java
  src/main/java/towssome/server/dto/CommunityPostSaveReq.java
  src/main/java/towssome/server/dto/CreatedPostRes.java
  src/main/java/towssome/server/dto/VoteAttributeReq.java
  src/main/java/towssome/server/entity/CommunityPost.java
  src/main/java/towssome/server/service/CommunityService.java
  src/main/java/towssome/server/service/VoteService.java
Labels: enhancement, fix

#47 해시태그 CRUD
  src/main/java/towssome/server/entity/HashTag.java
  src/main/java/towssome/server/entity/HashtagClassification.java
  src/main/java/towssome/server/repository/HashTagRepository.java
  src/main/java/towssome/server/repository/HashtagClassificationRepository.java
  src/main/java/towssome/server/service/HashtagService.java
Labels: enhancement, fix

#49 해시태그 추출 통합
  build.gradle
  src/main/java/towssome/server/ServerApplication.java
  src/main/java/towssome/server/config/AppConfig.java
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/HashtagDeleteReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/repository/HashtagClassificationRepository.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryCustom.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryImpl.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/repository/ViewLikeRepository.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/HashtagService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: enhancement

#57 무한스크롤 추가 구현
  src/main/java/towssome/server/controller/BookMarkController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/dto/CursorResult.java
  src/main/java/towssome/server/dto/ReviewListRes.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/repository/ReviewPostRepositoryCustom.java
  src/main/java/towssome/server/repository/ReviewPostRepositoryImpl.java
  src/main/java/towssome/server/repository/ViewLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/ViewLikeRepositoryImpl.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/SubscribeService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: enhancement

#58 메이팅/프로필태그/연인프로필/가상연인프로필 기능 추가
  .gitignore
  src/main/java/towssome/server/advice/ExceptionAdvice.java
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/MatingController.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/dto/CreateMateRes.java
  src/main/java/towssome/server/dto/CreateVirtualRes.java
  src/main/java/towssome/server/dto/HashtagRes.java
  src/main/java/towssome/server/dto/MatingRes.java
  src/main/java/towssome/server/dto/ProfileRes.java
  src/main/java/towssome/server/entity/Mating.java
  src/main/java/towssome/server/entity/ProfileTag.java
  src/main/java/towssome/server/entity/VirtualMateHashtag.java
  src/main/java/towssome/server/enumrated/MatingStatus.java
  src/main/java/towssome/server/exception/AlreadyExistMatingException.java
  src/main/java/towssome/server/exception/NotFoundMatingException.java
  src/main/java/towssome/server/jwt/JoinDTO.java
  src/main/java/towssome/server/jwt/JoinService.java
  src/main/java/towssome/server/python/hashtagmaker.py
  src/main/java/towssome/server/repository/HashTagRepository.java
  src/main/java/towssome/server/repository/MatingRepository.java
  src/main/java/towssome/server/repository/ProfileTagRepository.java
  src/main/java/towssome/server/repository/SubscribeRepositoryImpl.java
  src/main/java/towssome/server/repository/VirtualMateHashtagRepository.java
  src/main/java/towssome/server/service/MatingService.java
  src/main/java/towssome/server/service/MemberService.java
Labels: enhancement

#59 답변글 CRUD 추가
  .gitignore
  src/main/java/towssome/server/advice/ExceptionAdvice.java
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/controller/ReplyController.java
  src/main/java/towssome/server/dto/CreateReplyReq.java
  src/main/java/towssome/server/dto/CreateRes.java
  src/main/java/towssome/server/dto/ReplyRes.java
  src/main/java/towssome/server/dto/UpdateReplyReq.java
  src/main/java/towssome/server/entity/Reply.java
  src/main/java/towssome/server/exception/NotFoundReplyException.java
  src/main/java/towssome/server/exception/PageException.java
  src/main/java/towssome/server/repository/ReplyRepository.java
  src/main/java/towssome/server/service/PhotoService.java
  src/main/java/towssome/server/service/ReplyService.java
Labels: enhancement

#61 구독 페이지네이션으로 수정 + 리뷰글 속성 추가
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/버그-수정.md
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/SubscribeController.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/dto/SubscribePageDTO.java
  src/main/java/towssome/server/entity/BaseEntity.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/enumrated/ReviewType.java
  src/main/java/towssome/server/jwt/JwtStatic.java
  src/main/java/towssome/server/jwt/LoginFilter.java
  src/main/java/towssome/server/jwt/ReissueController.java
  src/main/java/towssome/server/repository/SubscribeRepository.java
  src/main/java/towssome/server/repository/SubscribeRepositoryCustom.java
  src/main/java/towssome/server/repository/SubscribeRepositoryImpl.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/SubscribeService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: enhancement, fix

#66 ReviewSimpleRes로 간단한 정보만 전송
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/ReviewSimpleRes.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: fix

#67 구독글 리스트 및 구독 계정 프로필 태그 조회 추가
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/SubscribeController.java
  src/main/java/towssome/server/dto/ProfileRes.java
  src/main/java/towssome/server/dto/ReviewSimpleRes.java
  src/main/java/towssome/server/dto/SubscribeRes.java
  src/main/java/towssome/server/entity/Subscribe.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/repository/ReviewPostRepositoryCustom.java
  src/main/java/towssome/server/repository/ReviewPostRepositoryImpl.java
  src/main/java/towssome/server/service/PhotoService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/SubscribeService.java
Labels: enhancement

#68 리뷰글 리스트 dto 수정 + id 생성 타입 수정
  src/main/java/towssome/server/dto/ReviewSimpleRes.java
  src/main/java/towssome/server/entity/Category.java
  src/main/java/towssome/server/entity/CommunityPost.java
  src/main/java/towssome/server/entity/HashtagClassification.java
  src/main/java/towssome/server/service/ReviewPostService.java
Labels: bug, fix

#69 해시태그 검색 무한스크롤 수정
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/CommentRes.java
  src/main/java/towssome/server/entity/CommentLike.java
  src/main/java/towssome/server/repository/CommentLikeRepository.java
  src/main/java/towssome/server/repository/CommentLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/CommentLikeRepositoryImpl.java
  src/main/java/towssome/server/repository/CommentRepositoryCustom.java
  src/main/java/towssome/server/repository/CommentRepositoryImpl.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryCustom.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryImpl.java
  src/main/java/towssome/server/service/CommentLikeService.java
  src/main/java/towssome/server/service/CommentService.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
Labels: fix

#71 comment 조회 무한스크롤 변경
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/CommentRes.java
  src/main/java/towssome/server/entity/CommentLike.java
  src/main/java/towssome/server/repository/CommentLikeRepository.java
  src/main/java/towssome/server/repository/CommentLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/CommentLikeRepositoryImpl.java
  src/main/java/towssome/server/repository/CommentRepositoryCustom.java
  src/main/java/towssome/server/repository/CommentRepositoryImpl.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryCustom.java
  src/main/java/towssome/server/repository/HashtagClassificationRepositoryImpl.java
  src/main/java/towssome/server/service/CommentLikeService.java
  src/main/java/towssome/server/service/CommentService.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
Labels: fix

#74 랭킹 구현
  src/main/java/towssome/server/ServerApplication.java
  src/main/java/towssome/server/advice/UtilScheduler.java
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/RankController.java
  src/main/java/towssome/server/dto/ProfileRes.java
  src/main/java/towssome/server/dto/RankerRes.java
  src/main/java/towssome/server/entity/Member.java
  src/main/java/towssome/server/entity/ViewLike.java
  src/main/java/towssome/server/repository/MemberRepository.java
  src/main/java/towssome/server/repository/MemberRepositoryCustom.java
  src/main/java/towssome/server/repository/MemberRepositoryImpl.java
  src/main/java/towssome/server/repository/ViewLikeRepository.java
  src/main/java/towssome/server/service/CommentService.java
  src/main/java/towssome/server/service/MemberService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: enhancement

#76 viewlike에 ReviewSimpleRes 적용
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: fix

#77 Swagger API 설명 추가
  src/main/java/towssome/server/config/CorsConfig.java
  src/main/java/towssome/server/controller/BookMarkController.java
  src/main/java/towssome/server/controller/CategoryController.java
  src/main/java/towssome/server/controller/CommentController.java
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/RankController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/SubscribeController.java
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/dto/CommentReq.java
  src/main/java/towssome/server/dto/PageResult.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/entity/Comment.java
  src/main/java/towssome/server/entity/CommunityPost.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/jwt/JoinService.java
  src/main/java/towssome/server/repository/HashTagRepository.java
  src/main/java/towssome/server/repository/HashTagRepositoryCustom.java
  src/main/java/towssome/server/repository/HashTagRepositoryImpl.java
  src/main/java/towssome/server/service/CommentService.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/HashtagService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/SubscribeService.java
Labels: enhancement

#79 access 토큰 만료시 에러메시지 수정
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/jwt/CustomAuthenticationException.java
  src/main/java/towssome/server/jwt/JwtFilter.java
  src/main/java/towssome/server/jwt/JwtStatic.java
  src/main/java/towssome/server/jwt/LoginFilter.java
Labels: fix

#80 카테고리 적용
  src/main/java/towssome/server/controller/ProfileController.java
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/ViewlikeController.java
  src/main/java/towssome/server/dto/ReviewPostReq.java
  src/main/java/towssome/server/dto/ReviewSimpleRes.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/repository/HashtagClassificationRepository.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/HashtagService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: fix

#81 스프링 시큐리티 cors 설정
  src/main/java/towssome/server/config/CorsConfig.java
  src/main/java/towssome/server/config/SecurityConfig.java
Labels: fix

#82 이메일 인증 기능 구현
  src/main/java/towssome/server/advice/ExceptionAdvice.java
  src/main/java/towssome/server/advice/UtilScheduler.java
  src/main/java/towssome/server/config/EmailConfig.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/dto/EmailCheckReq.java
  src/main/java/towssome/server/dto/EmailReq.java
  src/main/java/towssome/server/entity/EmailVerification.java
  src/main/java/towssome/server/exception/EmailSendException.java
  src/main/java/towssome/server/exception/ExpirationEmailException.java
  src/main/java/towssome/server/jwt/JoinService.java
  src/main/java/towssome/server/repository/EmailVerificationRepository.java
  src/main/java/towssome/server/service/MailSendService.java
Labels: enhancement

#83 해시태그 추출 수정
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/python/hashtagmaker.py
Labels: fix
