Repository TwoSSome/backend, pull requests merged in 2024-09, with the labels that each got.

#108 리뷰 수정 항목 추가, 좋아요 개수 반환
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/dto/ReviewPostRes.java
  src/main/java/towssome/server/dto/ReviewPostUpdateDto.java
  src/main/java/towssome/server/dto/ReviewPostUpdateReq.java
  src/main/java/towssome/server/dto/ReviewSimpleRes.java
  src/main/java/towssome/server/repository/ReviewPostRepository.java
  src/main/java/towssome/server/repository/ViewLikeRepositoryCustom.java
  src/main/java/towssome/server/repository/ViewLikeRepositoryImpl.java
  src/main/java/towssome/server/service/HashtagClassificationService.java
  src/main/java/towssome/server/service/ReviewPostService.java
  src/main/java/towssome/server/service/ViewlikeService.java
Labels: fix

#109 소셜 로그인 url 수정
  src/main/java/towssome/server/oauth2/CustomOAuth2UserService.java
  src/main/java/towssome/server/oauth2/CustomSuccessHandler.java
  src/main/java/towssome/server/repository/MemberRepository.java
Labels: fix

#110 스웨거 desc 추가 및 버그 수정
  src/main/java/towssome/server/controller/CategoryController.java
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/MatingController.java
  src/main/java/towssome/server/controller/ReplyController.java
  src/main/java/towssome/server/controller/VoteController.java
  src/main/java/towssome/server/dto/MatingIdReq.java
  src/main/java/towssome/server/dto/MatingRes.java
  src/main/java/towssome/server/dto/MemberNameReq.java
  src/main/java/towssome/server/entity/ReviewPost.java
  src/main/java/towssome/server/service/JoinService.java
Labels: bug, fix

#112 AT 30분 설정 / CORS 설정 수정
  src/main/java/towssome/server/advice/URLAdvice.java
  src/main/java/towssome/server/config/CorsConfig.java
  src/main/java/towssome/server/jwt/JwtStatic.java
Labels: fix

#113 스웨거 추가 및 코드 리팩토링
  src/main/java/towssome/server/advice/ServiceAdvice.java
  src/main/java/towssome/server/advice/UtilScheduler.java
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/controller/CommunityController.java
  src/main/java/towssome/server/controller/HashtagController.java
  src/main/java/towssome/server/controller/OAuthController.java
  src/main/java/towssome/server/controller/QuickRecommendController.java
  src/main/java/towssome/server/controller/ReplyController.java
  src/main/java/towssome/server/controller/VoteController.java
  src/main/java/towssome/server/dto/HashtagDeleteReq.java
  src/main/java/towssome/server/dto/OAuthInitialConfigReq.java
  src/main/java/towssome/server/jwt/ReissueController.java
  src/main/java/towssome/server/service/JoinService.java
  src/main/java/towssome/server/service/MemberService.java
  src/main/java/towssome/server/service/PhotoService.java
Labels: fix

#114 API 서버 git 리베이스 push
  gradlew
Labels: fix

#118 소셜 로그인 계정 초기화 수정
  src/main/java/towssome/server/entity/Member.java
Labels: fix

#119 카카오 소셜 로그인 완성
  src/main/java/towssome/server/controller/OAuthController.java
  src/main/java/towssome/server/entity/Member.java
  src/main/java/towssome/server/enumrated/SocialType.java
  src/main/java/towssome/server/oauth2/CustomOAuth2UserService.java
  src/main/java/towssome/server/oauth2/KakaoRes.java
Labels: enhancement

#121 ClusterEntity 수정
  src/main/java/towssome/server/entity/Cluster.java
Labels: fix
