Repository TwoSSome/backend, pull requests merged in 2025-01, with the labels that each got.

#184 feat(Calendar): 엔티티 추가
  src/main/java/towssome/server/entity/CalendarPersonalSchedule.java
  src/main/java/towssome/server/entity/CalendarPost.java
  src/main/java/towssome/server/entity/CalendarPostComment.java
  src/main/java/towssome/server/entity/CalendarSchedule.java
  src/main/java/towssome/server/entity/CalendarTag.java
  src/main/java/towssome/server/entity/Photo.java
Labels: enhancement

#185 캘린더 생성 시 기본 태그 6개 생성
  src/main/java/towssome/server/advice/ServiceAdvice.java
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/entity/CalendarPersonalSchedule.java
  src/main/java/towssome/server/entity/CalendarTag.java
  src/main/java/towssome/server/repository/CalendarPersonalScheduleRepository.java
  src/main/java/towssome/server/repository/CalendarPostCommentRepository.java
  src/main/java/towssome/server/repository/CalendarPostRepository.java
  src/main/java/towssome/server/repository/CalendarScheduleRepository.java
  src/main/java/towssome/server/repository/CalendarTagRepository.java
  src/main/java/towssome/server/service/CalendarService.java
  src/main/java/towssome/server/service/DeprecatedCalendarService.java
  src/main/java/towssome/server/service/MatingService.java
Labels: enhancement, fix

#186 build.gradel에서 jib build명 은닉
  .github/workflows/jib-build.yaml
  build.gradle
  src/main/java/towssome/server/repository/CalendarPersonalScheduleRepository.java
  src/main/java/towssome/server/repository/CalendarTagRepository.java
Labels: fix

#187 로그 남기기 추가
  .github/workflows/jib-build.yaml
  build.gradle
  src/main/java/towssome/server/controller/ReviewController.java
  src/main/java/towssome/server/controller/SubscribeController.java
  src/main/resources/application-prod.properties
Labels: enhancement

#196 feat(CalendarPost): 캘린더 게시글 CRUD 기능 완성
  src/main/java/towssome/server/advice/PhotoAdvice.java
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/controller/MemberController.java
  src/main/java/towssome/server/dto/CalendarPostDetailInfo.java
  src/main/java/towssome/server/dto/CreateCalendarPostDTO.java
  src/main/java/towssome/server/dto/CreateCalendarPostReq.java
  src/main/java/towssome/server/dto/CreateRes.java
  src/main/java/towssome/server/dto/UpdateCalendarPostDTO.java
  src/main/java/towssome/server/dto/UpdateCalendarPostReq.java
  src/main/java/towssome/server/entity/CalendarPost.java
  src/main/java/towssome/server/entity/Photo.java
  src/main/java/towssome/server/enumrated/PhotoType.java
  src/main/java/towssome/server/repository/PhotoRepository.java
  src/main/java/towssome/server/service/CalendarService.java
  src/main/java/towssome/server/service/CalendarServiceInterface.java
Labels: enhancement

#197 서버 재시작 workflow 추가
  .github/workflows/server-restart.yaml
Labels: enhancement

#198 feat(CalendarSchedule): 캘린더 일정 CRUD 완성
  src/main/java/towssome/server/advice/PhotoAdvice.java
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/dto/CalendarScheduleDetailInfo.java
  src/main/java/towssome/server/dto/CreateCalendarScheduleDTO.java
  src/main/java/towssome/server/dto/CreateCalendarScheduleReq.java
  src/main/java/towssome/server/dto/PostInSchedule.java
  src/main/java/towssome/server/dto/UpdateCalendarScheduleDTO.java
  src/main/java/towssome/server/dto/UpdateCalendarScheduleReq.java
  src/main/java/towssome/server/entity/CalendarSchedule.java
  src/main/java/towssome/server/repository/CalendarPostRepository.java
  src/main/java/towssome/server/service/CalendarService.java
  src/main/java/towssome/server/service/CalendarServiceInterface.java
Labels: enhancement

#201 게시글 코멘트에 baseentity 상속
  src/main/java/towssome/server/dto/CPCRes.java
  src/main/java/towssome/server/entity/CalendarPostComment.java
  src/main/java/towssome/server/service/CalendarService.java
Labels: fix

#203 feat(Calenar): 캘린더 월별 일정 조회 기능
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/dto/CalendarInfoByMonthDTO.java
  src/main/java/towssome/server/dto/CalendarScheduleInfo.java
  src/main/java/towssome/server/dto/MemberInfo.java
  src/main/java/towssome/server/entity/CalendarTag.java
  src/main/java/towssome/server/repository/CalendarScheduleRepository.java
  src/main/java/towssome/server/service/CalendarService.java
Labels: enhancement

#205 feat(Access_Token): 인가가 필요한 경로 접근 시에 액세스 토큰이 없으면 401에러를 반환하도록 설정
  src/main/java/towssome/server/config/SecurityConfig.java
  src/main/java/towssome/server/jwt/CustomAuthenticationEntryPoint.java
Labels: enhancement

#206 feat(CustomAuthenticationEntryPoint): 응답 인코딩 수정
  src/main/java/towssome/server/jwt/CustomAuthenticationEntryPoint.java
Labels: fix

#207 fix(CalendarPost): 게시글 타입 추가
  src/main/java/towssome/server/entity/CalendarPost.java
  src/main/java/towssome/server/enumrated/PostType.java
  src/main/java/towssome/server/service/CalendarService.java
Labels: fix

#209 연인 연동 예외 처리 추가
  src/main/java/towssome/server/repository/MatingRepository.java
  src/main/java/towssome/server/service/MatingService.java
Labels: fix

#210 사이드바 품품로그 & 월별 품품로그
  src/main/java/towssome/server/advice/ExceptionAdvice.java
  src/main/java/towssome/server/controller/CalendarController.java
  src/main/java/towssome/server/dto/PoomPoomLogInfo.java
  src/main/java/towssome/server/dto/SearchPoomPoomLogDTO.java
  src/main/java/towssome/server/dto/SearchPoomPoomLogInfo.java
  src/main/java/towssome/server/exception/InvalidMonthException.java
  src/main/java/towssome/server/repository/calendar_post/CalendarPostRepository.java
  src/main/java/towssome/server/repository/calendar_post/CalendarPostRepositoryCustom.java
  src/main/java/towssome/server/repository/calendar_post/CalendarPostRepositoryImpl.java
  src/main/java/towssome/server/service/CalendarService.java
  src/main/java/towssome/server/service/CalendarServiceInterface.java
Labels: enhancement

#212 fix(CORS): CORS 설정 수정
  src/main/java/towssome/server/advice/URLAdvice.java
Labels: bug, fix
